batch_size: 64
ckpt_dirpath: logs/sot-paper/SOT-512/f44i9icd-789/checkpoints
ckpt_path: null
configs:
- configs/synthetic_data/base.yaml
- configs/encoder/pesto_M=20_K=15.yaml
- configs/transform/stft_flat.yaml
- configs/synthetic_data/harmonic_1-8_16khz_preloaded.yaml
data:
  class_path: synthetic_data.PreloadedSinusoidDataModule
  init_args:
    data_path: data/40_1950_4096_04_1_4000_8_1_harmonic.pth
dataset: sinusoids-norm
group: SOT-512
log_dir: logs
loss: ''
model:
  baseline_gt_pitch: false
  decoder:
    class_path: synths.Sinusoidal
    init_args:
      amp_resample_method: window
      amp_scale_fn: null
      apply_roll_off: false
      freq_scale_fn: null
      harmonic: true
      n_samples: 4096
  detach_weights: false
  encoder:
    class_path: encoder.PESTOEncoder
    init_args:
      a_lrelu: 0.3
      activation_fn: leaky
      estimation_type: soft-argmax
      feature_size: 512
      harmonic: true
      kernel_size: 15
      n_bins_in: 285
      n_chan_input: 1
      n_chan_layers:
      - 40
      - 30
      - 30
      - 10
      - 3
      n_modes: 20
      n_prefilt_layers: 2
      num_output_layers: 1
      output_size: 285
      output_splits:
      - frequency
      - weights
      residual: true
  evaluation_metrics:
    diff_activated_partials: true
    log_spectral_distance: true
    mse: true
    mss: true
    octave_difference: true
    raw_chroma_accuracy: true
    raw_pitch_accuracy: true
  feature_extractor:
    bins_per_semitone: 3
    center: true
    fmin: 32.7
    hop_length: 256
    log: false
    n_bins: auto
    output_format: Complex
    pad_mode: constant
    type: cqt
  freq_hz_max: auto
  freq_hz_min: auto
  log_kwargs:
    idx:
    - 0
    - 1
  loss_fn:
    class_path: losses.MixOfLosses
    init_args:
      losses:
      - class_path: losses.MSSLoss
        init_args:
          fft_sizes:
          - 2048
          - 1024
          - 512
          - 256
          - 128
          - 64
          logmag_weight: 0
          loss_type: L1
          mag_weight: 1
      - class_path: losses.Wasserstein1D
        init_args:
          cumsum_only: false
          dont_normalize: true
          fixed_x: null
          hinge: false
          limit_quantile_range: true
          log_scaled_x: false
          p: 2
          require_sort: true
          square_dist: true
      weights:
      - 0.05
      - 1
  optimizer_init:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.0001
      weight_decay: 0.0001
  pretrain_loss_fn: []
  pretrain_steps: 0
  regularizations: []
  scheduler: null
  temperature: 0.1
  transform:
    center: true
    hop_length: 256
    log: false
    n_fft: 512
    output_format: Magnitude
    type: stft
    window: flattop
name: SOT-512-789
num_workers: 8
project: sot-paper
sample_rate: 16000
seed_everything: 789
trainer:
  accelerator: gpu
  accumulate_grad_batches: null
  amp_backend: null
  amp_level: null
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: null
  benchmark: null
  callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      auto_insert_metric_name: true
      dirpath: null
      every_n_epochs: null
      every_n_train_steps: null
      filename: best-lsd-{epoch}-{step}
      mode: min
      monitor: val_metrics/log_spectral_distance
      save_last: null
      save_on_train_epoch_end: null
      save_top_k: 1
      save_weights_only: false
      train_time_interval: null
      verbose: false
  check_val_every_n_epoch: 5
  default_root_dir: null
  detect_anomaly: false
  deterministic: null
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gpus: null
  gradient_clip_algorithm: null
  gradient_clip_val: null
  inference_mode: true
  ipus: null
  limit_predict_batches: null
  limit_test_batches: null
  limit_train_batches: null
  limit_val_batches: null
  log_every_n_steps: 20
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      group: SOT-512
      name: SOT-512-789
      project: sot-paper
      save_dir: logs/sot-paper/SOT-512
  max_epochs: 500
  max_steps: 25000
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 2
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  resume_from_checkpoint: null
  strategy: null
  sync_batchnorm: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: null
